version: '2'
services:
    app:
        build: .
        container_name: appServer
        environment:
            - NODE_ENV=development
            - PORT=3000
        command: "sh -c 'npm i && npm start'"
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"